name: Django Test with PostgreSQL Example

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main, pytest]
    pull_request:
        branches: [main, pytest]
jobs:
  simple_build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: pytest # Checkout with pytest branch
      - name: Create docker network
        run: |
          docker network create -d bridge our-library-net
      - name: Build django image
        run: |
          docker build -t my-django-image35:2.0.0 .
          - name: Run docker container postgres
        run: |
          docker-compose --env-file .env.stg up -d postgres_db04
      - name: Verifying net
        run: |
          docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" postgres04
      - name: Run docker container web
        run: |
          docker-compose --env-file .env.stg up -d web04
      - name: Run docker containers
        run: |
          docker-compose up --env-file .env.stg up --build
